on:
  workflow_call:
    inputs:
      mod:
        type: string
        required: true
      upload-url:
        type: string
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package mod ${{inputs.mod}} into tarball
        run: |
          tar -czf ${{inputs.mod}}.tar.gz ${{inputs.mod}}
      - name: Push pkg to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ${{inputs.mod}}.tar.gz
          asset_name: ${{inputs.mod}}.tar.gz
          asset_content_type: application/octet-stream
